### PR TITLE
fixed model checkpointer issue

### PR DESCRIPTION
**Pull request by milesjwinter**
Fixed and added back in the model checkpoint feature. Updated the docs

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Thanks for adding back in the checkpoint feature! It looks like some tests failed because `h5py` isn't included in `requirements/default.txt` &mdash; my bad. I've fixed this in #62. 

Also it looks like there are some `flake8` style issues (see https://travis-ci.org/WIPACrepo/decotools/jobs/303037813#L773-L789)

**Comment by jrbourbeau** [comment]
I noticed that `check_point` is `True` by default. I think I'd prefer it to be `False` by default. That way saving things to disk would be strictly an opt-in option for users. Do you have any thoughts on this?

**Comment by milesjwinter** [comment]
No serious objections, but there is really no circumstance under which you wouldn't want to checkpoint your model. But, as long as that's understood, it probably fine to change the default for the reasons you mention. It's also better for the tests to not have a file generated each time. Go ahead and change it. 

Miles

**Comment by jrbourbeau** [comment]
Thanks @milesjwinter!

**Pull request merged**
